openapi: '3.0.0'
info:
  version: '1.0.0'
  title: 'Dad Jokes API'
  description: Tell a goofy joke

paths:
  /hello:
    get:
      summary: health check
      responses:
        200:
          description: everything worked great
          content:
            application/json:
              schema:
                $ref: '#components/Schemas/HealthCheck'
  /api/v1/joke:
    get:
      summary: Get a joke
      responses:
        200:
          description: fetch a joke from our collection
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Joke'
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Greeting:
      type: object
      properties:
        hello:
          type: string
    GreetingObject:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Greeting'
    Joke:
      type: object
      properties:
        joke:
          type: string
    JokeObject:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Joke'
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
