openapi: 3.0.0
info:
  version: '0.1'
  title: 'Jokes'
  license:
    name: MIT
servers:
  - url: 'http://localhost:5000'
paths:
  /hello:
    get:
      summary: 'Simple hello world greeting'
      operationId: getGreeting
      responses:
        '200':
          description: 'simple greeting as a response'
          content:
            application/json:
              schema:
                $ref: '#components/schemas/GreetingObject'
  /api/v1/joke:
    get:
      summary: 'fetch a single joke'
      operationId: getJoke
      responses:
        '200':
          description: 'a single joke is returned'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/JokeObject'
        '500':
          description: 'something bad happened'
          content:
            application/json:
              schema:
                $ref: '#components/schemas/ErrorObject'
components:
  schemas:
    Greeting:
      type: object
      properties:
        hello:
          type: string
    GreetingObject:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Greeting'
    Joke:
      type: object
      properties:
        joke:
          type: string
    JokeObject:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Joke'
    Error:
      type: object
      required:
        - message
      properties:
        message:
          description: A human readable error message
          type: string
    Errorbject:
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Error'
